### Mostrar todos los usuarios
GET http://localhost:3000/users/

### Mostrar usuario según el ID
GET http://localhost:3000/users/1

### Agregar usuario
POST http://localhost:3000/users/
Content-Type: application/json

{
  "username": "Bry1307",
  "password": "Bry1307",
  "email": "bry13.0702mc@gmail.com"
}

### Actualizar usuario
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "username": "Bryan Morales"
}

### Eliminar usuario
DELETE http://localhost:3000/users/3

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "Bry13",
  "password": "Bry1307"
}

### Mostrar todos los miembros de staff
GET http://localhost:3000/staff

### Mostrar un miembro específico de staff por ID
GET http://localhost:3000/staff/2

### Agregar un nuevo miembro a staff
POST http://localhost:3000/staff
Content-Type: application/json

{
  "first_name": "Bry",
  "last_name": "Morales",
  "birth_date": "2002-12-07",
  "gender": "M",
  "phone_number": "2871010101",
  "email": "bry07mc@gamil.com",
  "address": "casa azul",
  "is_active": true,
  "user_id": 3
}

### Actualizar un miembro específico de staff
PUT http://localhost:3000/staff/2
Content-Type: application/json

{
  "first_name": "Bruno",
  "last_name": "Mars",
  "birth_date": "1985-10-08",
  "gender": "M",
  "phone_number": "1234567891",
  "email": "brunito@gmail.com",
  "address": "sabrá dios donde vive",
  "is_active": true,
  "user_id": 4
}

### Eliminar un miembro específico de staff por ID
DELETE http://localhost:3000/staff/4