GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios5

###
POST http://localhost:3000/usuarios/ 
content-type: application/json

{
"nombre": "Bry", 
"apellidos": "Contreras", 
"email": "bryan0702mc@gmail.com"
}

###
PUT http://localhost:3000/usuarios/2
content-type: application/json

{
  "nombre": "Bry", 
"apellidos": "Contreras", 
"email": "bryan0702mc@gmail.com"  
}