POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "bry13@gmail.com",
    "password": "bry0713"
}

###
GET http://localhost:3000/users/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaXNfYWRtaW4iOjEsImlhdCI6MTczNDMwMDA5NSwiZXhwIjoxNzM0MzAwMzk1fQ.l68_uTP5U1a4hdVAg4wRWGHvq8HjN4abipg-OdHEm50